import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Sidebar from '@/components/Sidebar';
import { red } from '@mui/material/colors';
import theme from "../components/Theme/Theme";
import { ThemeProvider, createTheme } from '@mui/material/styles';
import Topbar from '@/components/Topbar';



export default function Home() {
  return (
    <>
      <ThemeProvider theme={theme}>
        <Head>
          <title>Rejet next app</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/re.png" />
        </Head>
        <div>
          <Topbar />
          <Sidebar />
          <h2>Hello Here is the entry Point of our Application</h2>
        </div>
      </ThemeProvider>
    </>
  )
}
